// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {config} from '../models';
import {proxy} from '../models';

export function AddServer(arg1:server.ServerConfig):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetLogLines(arg1:number):Promise<Array<string>>;

export function GetProxyStatus():Promise<proxy.ProxyStatus>;

export function Greet(arg1:string):Promise<string>;

export function ListServers():Promise<Array<server.ServerConfig>>;

export function RemoveServer(arg1:string):Promise<void>;

export function StartProxy(arg1:string):Promise<void>;

export function StopProxy():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateServer(arg1:server.ServerConfig):Promise<void>;

export function ValidateServerName(arg1:string,arg2:string):Promise<void>;
